export const EMOJIS = {
  sadWorried: "😥",
  gear: "⚙️",
  creditCard: "💳",
  shirt: "👔",
  volunteer: "🙋",
  calendar: "📅",
  dollar: "💲",
  laptop: "💻",
  chart: "📊",
  invoice: "🧾",
  happy: "😄",
  edit: "✏️",
  trash: "🗑️",
  saving: "👩‍💻",
  sad: "☹️",
};
